! ##################################################################################################################################
! Begin MIT license text.
! _______________________________________________________________________________________________________
! Copyright 2022 Dr William R Case, Jr (mystransolver@gmail.com)
! End MIT license text.

   MODULE L6_WORKSPACE
   IMPLICIT NONE
   PRIVATE
   PUBLIC :: ALLOCATE_L6_2
   CONTAINS
      SUBROUTINE ALLOCATE_L6_2 ( NAME, CALLING_SUBR )
      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE
      USE CONSTANTS_1, ONLY           :  ZERO, ONEPP6
      USE IOUNT1, ONLY                :  WRT_ERR, ERR, F06
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, FATAL_ERR, NTERM_DLR, NTERM_PHIZL1
      USE SPARSE_MATRICES, ONLY       :  I2_DLR, I2_DLRt, I2_PHIZL1, I2_PHIZL1t
      USE FILE_LIFECYCLE, ONLY   :  OUTA_HERE
      USE DIAGNOSTICS_MEMORY_REPORTING, ONLY:  ALLOCATED_MEMORY
      IMPLICIT NONE
      CHARACTER(LEN=LEN(BLNK_SUB_NAM)):: SUBR_NAME = 'ALLOCATE_L6_2'
      CHARACTER(LEN=*), INTENT(IN)    :: CALLING_SUBR, NAME
      INTEGER(LONG)                   :: I, IERR, JERR, NROWS
      REAL(DOUBLE)                    :: CUR_MB_ALLOCATED, MB_ALLOCATED
      INTRINSIC                       :: REAL
      MB_ALLOCATED = ZERO
      JERR = 0
      IF (NAME == 'DLR') THEN
         NROWS = NTERM_DLR
         IF (ALLOCATED(I2_DLR)) THEN
            WRITE(ERR,990) SUBR_NAME, NAME; WRITE(F06,990) SUBR_NAME, NAME
            FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
         ELSE
            ALLOCATE (I2_DLR(NTERM_DLR),STAT=IERR)
            IF (IERR == 0) THEN
               DO I=1,NTERM_DLR; I2_DLR(I) = 0; ENDDO
            ELSE
               WRITE(ERR,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR; WRITE(F06,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR
               FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE IF (NAME == 'DLRt') THEN
         NROWS = NTERM_DLR
         IF (ALLOCATED(I2_DLRt)) THEN
            WRITE(ERR,990) SUBR_NAME, NAME; WRITE(F06,990) SUBR_NAME, NAME
            FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
         ELSE
            ALLOCATE (I2_DLRt(NTERM_DLR),STAT=IERR)
            IF (IERR == 0) THEN
               DO I=1,NTERM_DLR; I2_DLRt(I) = 0; ENDDO
            ELSE
               WRITE(ERR,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR; WRITE(F06,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR
               FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE IF (NAME == 'PHIZL1') THEN
         NROWS = NTERM_PHIZL1
         IF (ALLOCATED(I2_PHIZL1)) THEN
            WRITE(ERR,990) SUBR_NAME, NAME; WRITE(F06,990) SUBR_NAME, NAME
            FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
         ELSE
            ALLOCATE (I2_PHIZL1(NTERM_PHIZL1),STAT=IERR)
            IF (IERR == 0) THEN
               DO I=1,NTERM_PHIZL1; I2_PHIZL1(I) = 0; ENDDO
            ELSE
               WRITE(ERR,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR; WRITE(F06,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR
               FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE IF (NAME == 'PHIZL1t') THEN
         NROWS = NTERM_PHIZL1
         IF (ALLOCATED(I2_PHIZL1t)) THEN
            WRITE(ERR,990) SUBR_NAME, NAME; WRITE(F06,990) SUBR_NAME, NAME
            FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
         ELSE
            ALLOCATE (I2_PHIZL1t(NTERM_PHIZL1),STAT=IERR)
            IF (IERR == 0) THEN
               DO I=1,NTERM_PHIZL1; I2_PHIZL1t(I) = 0; ENDDO
            ELSE
               WRITE(ERR,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR; WRITE(F06,991) MB_ALLOCATED,NAME,SUBR_NAME,IERR
               FATAL_ERR = FATAL_ERR + 1; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE
         WRITE(ERR,915) SUBR_NAME, 'ALLOCATED', NAME; WRITE(F06,915) SUBR_NAME, 'ALLOCATED', NAME
         FATAL_ERR = FATAL_ERR + JERR; JERR = JERR + 1
      ENDIF
      IF (JERR /= 0) CALL OUTA_HERE ( 'Y' )
      MB_ALLOCATED = REAL(DOUBLE)*REAL(NROWS)/ONEPP6
      CALL ALLOCATED_MEMORY ( NAME, MB_ALLOCATED, 'ALLOC', 'Y', CUR_MB_ALLOCATED, SUBR_NAME )
 915 FORMAT(' *ERROR   915: PROGRAMMING ERROR IN SUBROUTINE ',A)
 990 FORMAT(' *ERROR   990: PROGRAMMING ERROR IN SUBROUTINE ',A)
 991 FORMAT(' *ERROR   991: CANNOT ALLOCATE ',F10.3,' MB TO ARRAY ',A)
      END SUBROUTINE ALLOCATE_L6_2

      SUBROUTINE DEALLOCATE_L6_2 ( NAME )

      USE PENTIUM_II_KIND, ONLY       :  BYTE, LONG, DOUBLE
      USE IOUNT1, ONLY                :  ERR, F06
      USE SCONTR, ONLY                :  BLNK_SUB_NAM, FATAL_ERR
      USE CONSTANTS_1, ONLY           :  ZERO
      USE SPARSE_MATRICES, ONLY       :  I2_DLR, I2_DLRt, I2_PHIZL1, I2_PHIZL1t
      USE FILE_LIFECYCLE, ONLY   :  OUTA_HERE
      USE DIAGNOSTICS_MEMORY_REPORTING, ONLY:  ALLOCATED_MEMORY

      IMPLICIT NONE

      CHARACTER(LEN=LEN(BLNK_SUB_NAM)):: SUBR_NAME = 'DEALLOCATE_L6_2'
      CHARACTER(LEN=*), INTENT(IN)    :: NAME
      INTEGER(LONG)                   :: IERR, JERR
      REAL(DOUBLE)                    :: CUR_MB_ALLOCATED

      JERR = 0
      IF (NAME == 'DLR') THEN
         IF (ALLOCATED(I2_DLR)) THEN
            DEALLOCATE (I2_DLR,STAT=IERR)
            IF (IERR /= 0) THEN
               WRITE(ERR,992) NAME,SUBR_NAME; WRITE(F06,992) NAME,SUBR_NAME; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE IF (NAME == 'DLRt') THEN
         IF (ALLOCATED(I2_DLRt)) THEN
            DEALLOCATE (I2_DLRt,STAT=IERR)
            IF (IERR /= 0) THEN
               WRITE(ERR,992) NAME,SUBR_NAME; WRITE(F06,992) NAME,SUBR_NAME; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE IF (NAME == 'PHIZL1') THEN
         IF (ALLOCATED(I2_PHIZL1)) THEN
            DEALLOCATE (I2_PHIZL1,STAT=IERR)
            IF (IERR /= 0) THEN
               WRITE(ERR,992) NAME,SUBR_NAME; WRITE(F06,992) NAME,SUBR_NAME; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE IF (NAME == 'PHIZL1t') THEN
         IF (ALLOCATED(I2_PHIZL1t)) THEN
            DEALLOCATE (I2_PHIZL1t,STAT=IERR)
            IF (IERR /= 0) THEN
               WRITE(ERR,992) NAME,SUBR_NAME; WRITE(F06,992) NAME,SUBR_NAME; JERR = JERR + 1
            ENDIF
         ENDIF
      ELSE
         WRITE(ERR,915) SUBR_NAME, 'ALLOCATED', NAME; WRITE(F06,915) SUBR_NAME, 'ALLOCATED', NAME
         FATAL_ERR = FATAL_ERR + JERR; JERR = JERR + 1
      ENDIF
      IF (JERR /= 0) THEN
         FATAL_ERR = FATAL_ERR + 1
         CALL OUTA_HERE ( 'Y' )
      ENDIF
      CALL ALLOCATED_MEMORY ( NAME, ZERO, 'DEALLOC', 'Y', CUR_MB_ALLOCATED, SUBR_NAME )

 915 FORMAT(' *ERROR   915: PROGRAMMING ERROR IN SUBROUTINE ',A)
 992 FORMAT(' *ERROR   992: CANNOT DEALLOCATE MEMORY FROM ARRAY ',A,' IN SUBROUTINE ',A)

      END SUBROUTINE DEALLOCATE_L6_2
   END MODULE L6_WORKSPACE
